vich_uploader:
  db_driver: orm
  mappings:
    post_images:
      uri_prefix: "%uploads_path%"
      upload_destination: "%kernel.project_dir%/public/%uploads_path%"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
    thumbnails:
      uri_prefix: "%uploads_path%"
      upload_destination: "%kernel.project_dir%/public/%uploads_path%"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
    jumbotrons:
      uri_prefix: "%uploads_path_jumbotron%"
      upload_destination: "%kernel.project_dir%/public/%uploads_path_jumbotron%"
      namer: Vich\UploaderBundle\Naming\UniqidNamer
